import 'package:flutter/material.dart';
import 'package:date_luv/l10n/generated/app_localizations.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import '../../core/utils/date_helper.dart';
import '../../core/constants/app_constants.dart';
import '../../core/theme/app_theme.dart';
import '../../data/models/milestone.dart';
import '../../data/repositories/app_provider.dart';
import '../../shared/widgets/common_widgets.dart';

class MilestoneFormScreen extends StatefulWidget {
  final Milestone? existingMilestone;
  const MilestoneFormScreen({super.key, this.existingMilestone});

  @override
  State<MilestoneFormScreen> createState() => _MilestoneFormScreenState();
}

class _MilestoneFormScreenState extends State<MilestoneFormScreen> {
  final _titleController = TextEditingController();
  final _descController = TextEditingController();
  String _selectedIcon = '🎉';
  DateTime _selectedDate = DateTime.now().add(const Duration(days: 30));
  bool _reminderEnabled = true;
  int _reminderDaysBefore = 1;
  bool _isSaving = false;

  bool get _isEditing => widget.existingMilestone != null;

  @override
  void initState() {
    super.initState();
    if (_isEditing) {
      final m = widget.existingMilestone!;
      _titleController.text = m.title;
      _descController.text = m.description ?? '';
      _selectedIcon = m.icon;
      _selectedDate = m.date;
      _reminderEnabled = m.reminderEnabled;
      _reminderDaysBefore = m.reminderDaysBefore;
    }
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descController.dispose();
    super.dispose();
  }

  Future<void> _selectDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime(2000),
      lastDate: DateTime(2100),
      builder: (ctx, child) => Theme(
        data: Theme.of(ctx).copyWith(
          colorScheme: const ColorScheme.dark(primary: AppColors.primary, surface: AppColors.darkCard),
        ),
        child: child!,
      ),
    );
    if (picked != null) setState(() => _selectedDate = picked);
  }

  Future<void> _save() async {
    final l10n = AppLocalizations.of(context)!;
    if (_titleController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(l10n.enterMilestoneName)),
      );
      return;
    }
    setState(() => _isSaving = true);
    final provider = context.read<AppProvider>();

    if (_isEditing) {
      final updated = Milestone(
        id: widget.existingMilestone!.id,
        title: _titleController.text.trim(),
        date: _selectedDate,
        description: _descController.text.trim().isEmpty ? null : _descController.text.trim(),
        isAutoGenerated: false,
        icon: _selectedIcon,
        reminderEnabled: _reminderEnabled,
        reminderDaysBefore: _reminderDaysBefore,
      );
      await provider.addMilestone(updated);
    } else {
      final m = provider.createEmptyMilestone();
      final newM = Milestone(
        id: m.id,
        title: _titleController.text.trim(),
        date: _selectedDate,
        description: _descController.text.trim().isEmpty ? null : _descController.text.trim(),
        isAutoGenerated: false,
        icon: _selectedIcon,
        reminderEnabled: _reminderEnabled,
        reminderDaysBefore: _reminderDaysBefore,
      );
      await provider.addMilestone(newM);
    }

    if (mounted) context.pop();
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;

    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            colors: AppColors.darkBgGradient,
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
          ),
        ),
        child: SafeArea(
          child: Column(
            children: [
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                child: Row(
                  children: [
                    IconButton(
                      onPressed: () => context.pop(),
                      icon: const Icon(Icons.arrow_back_ios_new, color: Colors.white),
                    ),
                    Expanded(
                      child: Text(
                        _isEditing ? l10n.editMilestone : l10n.addMilestone,
                        style: const TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.w700),
                      ),
                    ),
                    TextButton(
                      onPressed: _isSaving ? null : _save,
                      child: Text(
                        _isSaving ? l10n.saving : l10n.save,
                        style: const TextStyle(color: AppColors.secondary, fontWeight: FontWeight.w700, fontSize: 16),
                      ),
                    ),
                  ],
                ),
              ),

              Expanded(
                child: SingleChildScrollView(
                  padding: const EdgeInsets.symmetric(horizontal: 24),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Icon picker
                      Text(l10n.icon, style: const TextStyle(color: AppColors.textMuted, fontSize: 13, fontWeight: FontWeight.w600)),
                      const SizedBox(height: 8),
                      Wrap(
                        spacing: 8,
                        runSpacing: 8,
                        children: AppConstants.milestoneIcons.map((icon) {
                          final isSelected = _selectedIcon == icon;
                          return GestureDetector(
                            onTap: () => setState(() => _selectedIcon = icon),
                            child: AnimatedContainer(
                              duration: const Duration(milliseconds: 200),
                              padding: const EdgeInsets.all(10),
                              decoration: BoxDecoration(
                                color: isSelected ? AppColors.secondary.withValues(alpha: 0.2) : AppColors.darkCard,
                                borderRadius: BorderRadius.circular(12),
                                border: Border.all(
                                  color: isSelected ? AppColors.secondary : Colors.transparent,
                                  width: 2,
                                ),
                              ),
                              child: Text(icon, style: const TextStyle(fontSize: 24)),
                            ),
                          );
                        }).toList(),
                      ),
                      const SizedBox(height: 20),

                      // Title
                      TextField(
                        controller: _titleController,
                        style: const TextStyle(color: Colors.white),
                        decoration: InputDecoration(
                          labelText: l10n.milestoneName,
                          prefixIcon: const Icon(Icons.event_outlined, color: AppColors.textMuted),
                        ),
                      ),
                      const SizedBox(height: 16),

                      // Description
                      TextField(
                        controller: _descController,
                        style: const TextStyle(color: Colors.white),
                        maxLines: 3,
                        decoration: InputDecoration(
                          labelText: l10n.notes,
                          prefixIcon: const Icon(Icons.notes_outlined, color: AppColors.textMuted),
                        ),
                      ),
                      const SizedBox(height: 16),

                      // Date
                      GlassCard(
                        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                        child: GestureDetector(
                          onTap: _selectDate,
                          behavior: HitTestBehavior.opaque,
                          child: Row(
                            children: [
                              const Icon(Icons.calendar_today_outlined, color: AppColors.secondary, size: 20),
                              const SizedBox(width: 12),
                              Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(l10n.date, style: const TextStyle(color: AppColors.textMuted, fontSize: 12)),
                                  Text(
                                    DateHelper.formatDateShort(_selectedDate, l10n.localeName),
                                    style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w700, fontSize: 16),
                                  ),
                                ],
                              ),
                              const Spacer(),
                              const Icon(Icons.edit_outlined, color: AppColors.textMuted),
                            ],
                          ),
                        ),
                      ),
                      const SizedBox(height: 20),

                      // Reminder settings
                      GlassCard(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              children: [
                                const Icon(Icons.notifications_outlined, color: AppColors.secondary),
                                const SizedBox(width: 12),
                                Expanded(
                                  child: Text(l10n.reminder, style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w700)),
                                ),
                                Switch(
                                  value: _reminderEnabled,
                                  onChanged: (v) => setState(() => _reminderEnabled = v),
                                  activeThumbColor: AppColors.secondary,
                                ),
                              ],
                            ),
                            if (_reminderEnabled) ...[
                              const SizedBox(height: 12),
                              Text(l10n.remindBefore, style: const TextStyle(color: AppColors.textMuted, fontSize: 13)),
                              const SizedBox(height: 8),
                              Wrap(
                                spacing: 8,
                                children: [1, 2, 3, 5, 7].map((days) {
                                  final isSelected = _reminderDaysBefore == days;
                                  return GestureDetector(
                                    onTap: () => setState(() => _reminderDaysBefore = days),
                                    child: AnimatedContainer(
                                      duration: const Duration(milliseconds: 200),
                                      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
                                      decoration: BoxDecoration(
                                        color: isSelected ? AppColors.secondary : AppColors.darkCard,
                                        borderRadius: BorderRadius.circular(10),
                                      ),
                                      child: Text(
                                        l10n.daysCount(days),
                                        style: TextStyle(
                                          color: isSelected ? Colors.white : Colors.white70,
                                          fontWeight: FontWeight.w600,
                                          fontSize: 13,
                                        ),
                                      ),
                                    ),
                                  );
                                }).toList(),
                              ),
                            ],
                          ],
                        ),
                      ),

                      const SizedBox(height: 40),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
