import 'package:hive/hive.dart';

part 'milestone.g.dart';

@HiveType(typeId: 2)
class Milestone extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String title;

  @HiveField(2)
  DateTime date;

  @HiveField(3)
  String? description;

  @HiveField(4)
  bool isAutoGenerated;

  @HiveField(5)
  String icon;

  @HiveField(6)
  bool reminderEnabled;

  @HiveField(7)
  int reminderDaysBefore;

  Milestone({
    required this.id,
    required this.title,
    required this.date,
    this.description,
    this.isAutoGenerated = false,
    this.icon = '🎉',
    this.reminderEnabled = true,
    this.reminderDaysBefore = 1,
  });
}
