name: Build Android APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: flutter build apk --android-skip-build-dependency-validation

      - uses: actions/upload-artifact@v4
        with:
          name: dateLuv-apk
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/apk/release/*.apk
          if-no-files-found: warn
